FROM ubuntu:22.04

RUN apt update
RUN apt install -y easy-rsa openvpn openssl ufw joe patch
RUN apt install -y openssh-server net-tools

RUN useradd ca_user

COPY _openvpn_certificate_creation.sh /
COPY _openvpn_start.sh /
RUN chmod u+x /*.sh
