# Use the specified PyTorch image as the base
ARG PYTORCH_IMAGE=pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime
FROM ${PYTORCH_IMAGE}

# Specify the NVFlare version
ARG NVF_VERSION=2.4.1
ENV NVF_BRANCH=${NVF_VERSION}

# Set the Python version
ENV PYTHON_VERSION=3.10.14

# Install specific versions of pip and setuptools
RUN python3 -m pip install -U pip==23.3.1
RUN python3 -m pip install -U setuptools==69.5.1

# Install additional Python packages and dependencies at defined versions
RUN python3 -m pip install \
    matplotlib==3.7.2 \
    openpyxl==3.1.0 \
    protobuf==3.20.3 \
    pytorch-lightning==1.9.0 \
    scikit-learn==1.3.0 \
    torchvision==0.17.0 \
    tqdm==4.65.0 \
    torchio==0.19.6 \
    seaborn==0.12.2 \
    timm==0.9.16 \
    SimpleITK==2.2.1 \
    pydicom==2.4.4 \
    monai==1.3.0 \
    tensorboard==2.12.1 \
    Deprecated==1.2.14 \
    absl-py==2.1.0 \
    aiohttp==3.9.5 \
    aiosignal==1.3.1 \
    async-timeout==4.0.3 \
    cachetools==5.3.3 \
    contourpy==1.2.1 \
    cycler==0.12.1 \
    et-xmlfile==1.1.0 \
    fonttools==4.53.1 \
    frozenlist==1.4.1 \
    google-auth==2.31.0 \
    google-auth-oauthlib==1.0.0 \
    grpcio==1.64.1 \
    huggingface_hub==0.23.4 \
    humanize==4.9.0 \
    joblib==1.4.2 \
    kiwisolver==1.4.5 \
    lightning-utilities==0.11.3.post0 \
    markdown==3.6 \
    markdown-it-py==3.0.0 \
    mdurl==0.1.2 \
    multidict==6.0.5 \
    nibabel==5.2.1 \
    oauthlib==3.2.2 \
    pandas==2.2.2 \
    pyasn1==0.6.0 \
    pyasn1-modules==0.4.0 \
    pyparsing==3.0.9 \
    python-dateutil==2.9.0.post0 \
    requests-oauthlib==2.0.0 \
    rich==13.7.1 \
    rsa==4.9 \
    safetensors==0.4.3 \
    scipy==1.14.0 \
    shellingham==1.5.4 \
    tensorboard-data-server==0.7.2 \
    tensorboard-plugin-wit==1.8.1 \
    threadpoolctl==3.5.0 \
    torchmetrics==1.4.0.post0 \
    typer==0.12.3 \
    tzdata==2024.1 \
    werkzeug==3.0.3 \
    wrapt==1.16.0 \
    yarl==1.9.4

# Set the working directory
WORKDIR /workspace/

# Copy the modified NVFlare source code into the image
# (Assuming you have your modified nvflare source code in a local directory named 'nvflare')
COPY ./docker_config/NVFlare /workspace/nvflare

# Install NVFlare from the local source and dependencies at defined versions (except nvflare-nightly)
RUN python3 -m pip install \
    /workspace/nvflare \
    nvflare-nightly \
    Flask==3.0.2 \
    Flask-JWT-Extended==4.6.0 \
    Flask-SQLAlchemy==3.1.1 \
    PyJWT==2.8.0 \
    SQLAlchemy==2.0.16 \
    Werkzeug==3.0.1 \
    blinker==1.8.2 \
    docker==7.1.0 \
    greenlet==3.0.3 \
    grpcio==1.62.1 \
    gunicorn==22.0.0 \
    itsdangerous==2.2.0 \
    msgpack==1.0.8 \
    protobuf==4.24.4 \
    psutil==6.0.0 \
    pyhocon==0.3.61 \
    websockets==12.0

# COPY ./NVFlare/dashboard /workspace/nvflare/dashboard

COPY ./controller /workspace/controller
# Install the controller package
RUN python3 -m pip install /workspace/controller

# Set python path
ENV PYTHONPATH=/workspace/controller/controller

# Set the Docker image name
LABEL name="nvflare-pt-dev:3dcnn"
