# Use the specified PyTorch image as the base
ARG PYTORCH_IMAGE=pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime
FROM ${PYTORCH_IMAGE}

# Specify the NVFlare version
ARG NVF_VERSION=2.4.1
ENV NVF_BRANCH=${NVF_VERSION}

# Set the Python version
ENV PYTHON_VERSION=3.10.14

# Install specific versions of pip and setuptools
RUN python3 -m pip install -U pip==23.3.1
RUN python3 -m pip install -U setuptools==69.5.1

# Install additional Python packages
RUN python3 -m pip install torchvision==0.14.0 tensorboard==2.16.2

# Install NVFlare from the local source and nvflare-nightly (not at fixed version)
# (Assuming you have your modified nvflare source code in a local directory named 'nvflare')
WORKDIR /workspace/
COPY ./docker_config/NVFlare /workspace/nvflare
RUN python -m pip install /workspace/nvflare
RUN rm -rf /workspace/nvflare

# TODO is this needed in addition to the copy operation above?
COPY ./docker_config/NVFlare/dashboard /workspace/nvflare/dashboard

# Install the controller package
COPY ../controller /workspace/controller
RUN python -m pip install /workspace/controller
RUN rm -rf /workspace/controller

# Set the Docker image name
LABEL name="nvflare-pt-dev:cifar10"
