FROM nvflare-pt-dev:3dcnn

# for testing coverage in our own tests
RUN python3 -m pip install coverage==7.5.4

# fixed versions of packages installed for nvflare tests (except nvflare-nightly)
RUN python3 -m pip install \
    nvflare-nightly \
    Mako==1.3.5 \
    alabaster==0.7.16 \
    alembic==1.13.2 \
    aniso8601==9.0.1 \
    antlr4-python3-runtime==4.9.3 \
    babel==2.15.0 \
    black==22.10.0 \
    click==8.1.3 \
    cloudpickle==3.0.0 \
    commonmark==0.9.1 \
    docker-pycreds==0.4.0 \
    docutils==0.20.1 \
    entrypoints==0.4 \
    execnet==2.1.1 \
    flake8==5.0.4 \
    gitdb==4.0.11 \
    gitpython==3.1.43 \
    graphene==3.3 \
    graphql-core==3.2.3 \
    graphql-relay==3.2.0 \
    imagesize==1.4.1 \
    importlib-metadata==7.1.0 \
    iniconfig==2.0.0 \
    isort==5.10.1 \
    mccabe==0.7.0 \
    mlflow==2.14.2 \
    mock==5.1.0 \
    mypy-extensions==1.0.0 \
    nvidia-nccl-cu12==2.22.3 \
    omegaconf==2.3.0 \
    openmined.psi==1.1.1 \
    opentelemetry-api==1.25.0 \
    opentelemetry-sdk==1.25.0 \
    opentelemetry-semantic-conventions==0.46b0 \
    pathspec==0.12.1 \
    pluggy==1.5.0 \
    pyarrow==15.0.2 \
    pycodestyle==2.9.1 \
    pyflakes==2.5.0 \
    pytest==8.2.2 \
    pytest-cov==4.0.0 \
    pytest-xdist==3.0.2 \
    querystring-parser==1.2.4 \
    recommonmark==0.7.1 \
    sentry-sdk==2.8.0 \
    setproctitle==1.3.3 \
    smmap==5.0.1 \
    snowballstemmer==2.2.0 \
    sphinx==7.3.7 \
    sphinx-copybutton==0.5.2 \
    sphinx-rtd-theme==2.0.0 \
    sphinxcontrib-applehelp==1.0.8 \
    sphinxcontrib-devhelp==1.0.6 \
    sphinxcontrib-htmlhelp==2.0.5 \
    sphinxcontrib-jquery==4.1 \
    sphinxcontrib-jsmath==1.0.1 \
    sphinxcontrib-qthelp==1.0.7 \
    sphinxcontrib-serializinghtml==1.1.10 \
    sqlparse==0.5.0 \
    tenseal==0.3.12 \
    wandb==0.17.4 \
    xgboost==2.1.0 \
    zipp==3.19.2

# additional package needed for [black]jupyter
RUN python3 -m pip install tokenize-rt==5.2.0

RUN mkdir /scratch
RUN chmod a+rwx /scratch

ENV PYTHONPATH=/workspace/controller/controller

LABEL name="nvflare-pt-dev:testing"
