# Use a simple base image
FROM python:3.10-slim

# Specify the NVFlare version
ARG NVF_VERSION=2.4.1
ENV NVF_BRANCH=${NVF_VERSION}

# Set the Python version
ENV PYTHON_VERSION=3.10.14

# Install specific versions of pip and setuptools
RUN python -m pip install -U pip==23.3.1 \
    && python -m pip install -U setuptools==69.5.1

# Install Docker and zip
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    zip \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
    && echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && apt-get install -y docker-ce docker-ce-cli containerd.io \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /workspace/

# Copy the modified NVFlare source code into the image
# (Assuming you have your modified nvflare source code in a local directory named 'nvflare')
COPY ./NVFlare /workspace/nvflare


# Install NVFlare from the local source
RUN python -m pip install /workspace/nvflare

COPY ./NVFlare/dashboard /workspace/nvflare/dashboard

COPY ../controller /workspace/controller
# Set python path
ENV PYTHONPATH=/workspace/controller/controller

# Set the Docker image name
LABEL name="nvflare-pt-dev:nfcore"

# Optional: expose a port or set any other necessary environment variables
EXPOSE 443
# ENV SOME_ENV_VARIABLE=some_value
