# Use the specified PyTorch image as the base
ARG PYTORCH_IMAGE=pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime
FROM ${PYTORCH_IMAGE}

# Specify the NVFlare version
ARG NVF_VERSION=2.4.1
ENV NVF_BRANCH=${NVF_VERSION}

# Set the Python version
ENV PYTHON_VERSION=3.10.14

# Install updates of installed packages
RUN apt update

RUN apt install -y \
    apt=2.4.14 \
    apt-utils=2.4.14 \
    libapt-pkg6.0=2.4.14

# Install python and dependencies
RUN apt install -y \
    libexpat1=2.4.7-1ubuntu0.7 \
    libmpdec3=2.5.1-2build2 \
    libpython3-stdlib=3.10.6-1~22.04.1 \
    libpython3.10-minimal=3.10.12-1~22.04.14 \
    libpython3.10-stdlib=3.10.12-1~22.04.14 \
    libreadline8=8.1.2-1 \
    libsqlite3-0=3.37.2-2ubuntu0.5 \
    media-types=7.0.0 \
    python3-minimal=3.10.6-1~22.04.1 \
    python3.10-minimal=3.10.12-1~22.04.14 \
    python3.10=3.10.12-1~22.04.14 \
    python3=3.10.6-1~22.04.1 \
    readline-common=8.1.2-1

# uninstall conda to prevent usage and avoid and potential repository license issues
RUN python3 -m pip uninstall -y conda conda-package-handling conda_index

# Install specific versions of pip and setuptools
RUN python3 -m pip install \
    -U \
    pip==25.2 \
    setuptools==80.8.0

# Install dependencies of NVFlare at fixed versions
RUN python3 -m pip install \
    --upgrade \
    psutil==7.0.0
RUN python3 -m pip install \
    Flask==3.0.2 \
    Flask-JWT-Extended==4.6.0 \
    Flask-SQLAlchemy==3.1.1 \
    PyJWT==2.10.1 \
    SQLAlchemy==2.0.16 \
    Werkzeug==3.0.1 \
    blinker==1.9.0 \
    docker==7.1.0 \
    greenlet==3.2.2 \
    grpcio==1.62.1 \
    gunicorn==23.0.0 \
    itsdangerous==2.2.0 \
    msgpack==1.1.0 \
    protobuf==4.24.4 \
    pyhocon==0.3.61 \
    pyparsing==3.2.3 \
    websockets==15.0.1

# Install additional Python packages for application code at defined versions
RUN python3 -m pip install \
    Deprecated==1.2.18 \
    SimpleITK==2.5.0 \
    absl-py==2.2.2 \
    aiohttp==3.11.18 \
    aiosignal==1.3.2 \
    async-timeout==5.0.1 \
    cachetools==5.5.2 \
    contourpy==1.3.2 \
    cycler==0.12.1 \
    et-xmlfile==2.0.0 \
    fonttools==4.58.0 \
    frozenlist==1.6.0 \
    google-auth-oauthlib==1.2.2 \
    google-auth==2.40.2 \
    huggingface_hub==0.29.3 \
    datasets==3.4.1 \
    coral_pytorch==1.4.0 \
    humanize==4.12.3 \
    joblib==1.5.1 \
    kiwisolver==1.4.8 \
    lightning-utilities==0.14.3 \
    markdown-it-py==3.0.0 \
    markdown==3.8 \
    matplotlib==3.9.2 \
    mdurl==0.1.2 \
    monai==1.4.0 \
    multidict==6.4.4 \
    nibabel==5.3.2 \
    oauthlib==3.2.2 \
    openpyxl==3.1.5 \
    pandas==2.2.3 \
    numpy==1.26.4 \
    pyasn1-modules==0.4.2 \
    pyasn1==0.6.1 \
    pydicom==3.0.1 \
    python-dateutil==2.9.0.post0 \
    x-transformers==2.3.5 \
    pytorch-lightning==2.4.0 \
    requests==2.32.3 \
    requests-oauthlib==2.0.0 \
    rich==14.0.0 \
    rsa==4.9.1 \
    safetensors==0.5.3 \
    scikit-learn==1.5.2 \
    scipy==1.15.3 \
    seaborn==0.13.2 \
    wandb==0.18.6 \
    einops==0.8.0 \
    shellingham==1.5.4 \
    tensorboard-data-server==0.7.2 \
    tensorboard-plugin-wit==1.8.1 \
    tensorboard==2.19.0 \
    threadpoolctl==3.6.0 \
    timm==1.0.15 \
    torchio==0.20.1 \
    torchmetrics==1.7.1 \
    torchvision==0.17.2 \
    torchaudio==2.2.2 \
    tqdm==4.67.0 \
    typer==0.15.4 \
    tzdata==2025.2 \
    wrapt==1.17.2 \
    yarl==1.20.0 \
    aiohappyeyeballs==2.6.1 \
    annotated-types==0.7.0 \
    dill==0.3.8 \
    docker-pycreds==0.4.0 \
    einx==0.3.0 \
    frozendict==2.4.6 \
    gitdb==4.0.12 \
    gitpython==3.1.44 \
    hf-xet==1.1.2 \
    importlib-resources==6.5.2 \
    loguru==0.7.3 \
    multiprocess==0.70.16 \
    propcache==0.3.1 \
    pyarrow==20.0.0 \
    pydantic==2.11.5 \
    pydantic-core==2.33.2 \
    sentry-sdk==2.29.1 \
    setproctitle==1.3.6 \
    smmap==5.0.2 \
    typing-extensions==4.13.2 \
    typing-inspection==0.4.1 \
    xxhash==3.5.0

# Install packages needed for listing licenses of installed pip packages
RUN python3 -m pip install \
    pip-licenses==5.0.0 \
    prettytable==3.16.0

# Install packages needed for creating SBOM of apt packages
RUN python3 -m pip install \
    defusedxml==0.7.1 \
    distro2sbom==0.6.0 \
    lib4sbom==0.8.4 \
    semantic-version==2.10.0

# Clean up pip cache
RUN python3 -m pip cache purge

# Update versions of installed packages
RUN apt install -y \
    base-files=12ubuntu4.7 \
    bash=5.1-6ubuntu1.1 \
    bsdutils=1:2.37.2-4ubuntu3.4 \
    ca-certificates=20240203~22.04.1 \
    coreutils=8.32-4.1ubuntu1.2 \
    dpkg=1.21.1ubuntu2.6 \
    e2fsprogs=1.46.5-2ubuntu1.2 \
    gpgv=2.2.27-3ubuntu2.5 \
    libblkid1=2.37.2-4ubuntu3.4 \
    libc-bin=2.35-0ubuntu3.13 \
    libc-dev-bin=2.35-0ubuntu3.13 \
    libc6-dev=2.35-0ubuntu3.13 \
    libc6=2.35-0ubuntu3.13 \
    libcap2=1:2.44-1ubuntu0.22.04.2 \
    libcom-err2=1.46.5-2ubuntu1.2 \
    libext2fs2=1.46.5-2ubuntu1.2 \
    libgnutls30=3.7.3-4ubuntu1.7 \
    libgssapi-krb5-2=1.19.2-2ubuntu0.7 \
    libk5crypto3=1.19.2-2ubuntu0.7 \
    libkrb5-3=1.19.2-2ubuntu0.7 \
    libkrb5support0=1.19.2-2ubuntu0.7 \
    libmount1=2.37.2-4ubuntu3.4 \
    libpam-modules-bin=1.4.0-11ubuntu2.6 \
    libpam-modules=1.4.0-11ubuntu2.6 \
    libpam-runtime=1.4.0-11ubuntu2.6 \
    libpam0g=1.4.0-11ubuntu2.6 \
    libseccomp2=2.5.3-2ubuntu3~22.04.1 \
    libsmartcols1=2.37.2-4ubuntu3.4 \
    libss2=1.46.5-2ubuntu1.2 \
    libssl3=3.0.2-0ubuntu1.21 \
    libsystemd0=249.11-0ubuntu3.17 \
    libtasn1-6=4.18.0-4ubuntu0.2 \
    libudev1=249.11-0ubuntu3.17 \
    libuuid1=2.37.2-4ubuntu3.4 \
    linux-libc-dev=5.15.0-170.180 \
    logsave=1.46.5-2ubuntu1.2 \
    mount=2.37.2-4ubuntu3.4 \
    openssl=3.0.2-0ubuntu1.21 \
    util-linux=2.37.2-4ubuntu3.4

# Install apt-transport-https curl gnupg lsb-release zip and dependencies at defined versions
RUN apt install -y \
    apt-transport-https=2.4.14 \
    curl=7.81.0-1ubuntu1.21 \
    dirmngr=2.2.27-3ubuntu2.5 \
    distro-info-data=0.52ubuntu0.11 \
    gnupg-l10n=2.2.27-3ubuntu2.5 \
    gnupg-utils=2.2.27-3ubuntu2.5 \
    gnupg=2.2.27-3ubuntu2.5 \
    gpg-agent=2.2.27-3ubuntu2.5 \
    gpg-wks-client=2.2.27-3ubuntu2.5 \
    gpg-wks-server=2.2.27-3ubuntu2.5 \
    gpg=2.2.27-3ubuntu2.5 \
    gpgconf=2.2.27-3ubuntu2.5 \
    gpgsm=2.2.27-3ubuntu2.5 \
    libassuan0=2.5.5-1build1 \
    libbrotli1=1.0.9-2build6 \
    libcurl4=7.81.0-1ubuntu1.21 \
    libksba8=1.6.0-2ubuntu0.2 \
    libldap-2.5-0=2.5.20+dfsg-0ubuntu0.22.04.1 \
    libldap-common=2.5.20+dfsg-0ubuntu0.22.04.1 \
    libnghttp2-14=1.43.0-1ubuntu0.2 \
    libnpth0=1.6-3build2 \
    libpsl5=0.21.0-1.2build2 \
    librtmp1=2.4+20151223.gitfa8646d.1-2build4 \
    libsasl2-2=2.1.27+dfsg2-3ubuntu1.2 \
    libsasl2-modules-db=2.1.27+dfsg2-3ubuntu1.2 \
    libsasl2-modules=2.1.27+dfsg2-3ubuntu1.2 \
    libssh-4=0.9.6-2ubuntu0.22.04.5 \
    lsb-release=11.1.0ubuntu4 \
    pinentry-curses=1.1.1-1build2 \
    publicsuffix=20211207.1025-1 \
    unzip=6.0-26ubuntu3.2 \
    zip=3.0-12build2

# Clean up apt cache
RUN rm -rf /var/lib/apt/lists/*

# install ODELIA fork of NVFlare from local source
WORKDIR /workspace/
COPY ./MediSwarm/docker_config/NVFlare /workspace/nvflare
## use startup kit template in the dashboard
COPY ./MediSwarm/docker_config/master_template.yml /workspace/nvflare/nvflare/lighter/impl/
RUN python3 -m pip install /workspace/nvflare
RUN rm -rf /workspace/nvflare

# Copy the source code for local training and deploying to the swarm
COPY ./MediSwarm /MediSwarm
RUN mkdir -p /fl_admin/transfer
RUN ln -s /MediSwarm /fl_admin/transfer/MediSwarm

# Copy pre-trained model weights to image
COPY ./torch_home_cache /torch_home

# allow creating home directory for local user inside container if needed
RUN chmod a+rwx /home
