# Use the specified PyTorch image as the base
ARG PYTORCH_IMAGE=pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime
FROM ${PYTORCH_IMAGE}

# Specify the NVFlare version
ARG NVF_VERSION=2.4.1
ENV NVF_BRANCH=${NVF_VERSION}

# Set the Python version
ENV PYTHON_VERSION=3.10.14

# Install specific versions of pip and setuptools
RUN python3 -m pip install -U pip==23.3.1 setuptools==69.5.1

# Install additional Python packages and dependencies at defined versions
RUN python3 -m pip install \
    pytorch-lightning==2.4.0 \
    torchio==0.20.1 \
    monai==1.4.0 \
    pandas==2.2.3 \
    numpy==1.26.4 \
    tqdm==4.67.0 \
    openpyxl==3.1.5 \
    scikit-learn==1.5.2 \
    matplotlib==3.9.2 \
    seaborn==0.13.2 \
    wandb==0.18.6 \
    einops==0.8.0 \
    pydicom==3.0.1 \
    torchvision==0.17.2 \
    torchaudio==2.2.2 \
    protobuf==3.20.3 \
    pytorch-cuda==12.1 \
    -e .

# Install dependencies of NVFlare at defined versions
RUN python3 -m pip install \
    Flask==3.0.2 \
    Flask-JWT-Extended==4.6.0 \
    Flask-SQLAlchemy==3.1.1 \
    PyJWT==2.8.0 \
    SQLAlchemy==2.0.16 \
    Werkzeug==3.0.1 \
    blinker==1.8.2 \
    docker==7.1.0 \
    greenlet==3.0.3 \
    grpcio==1.62.1 \
    gunicorn==22.0.0 \
    itsdangerous==2.2.0 \
    msgpack==1.0.8 \
    protobuf==4.24.4 \
    psutil==6.0.0 \
    pyhocon==0.3.61 \
    websockets==12.0

# Install NVFlare from the local source and nvflare-nightly
WORKDIR /workspace/
COPY ./docker_config/NVFlare /workspace/nvflare
RUN python3 -m pip install /workspace/nvflare nvflare-nightly
RUN rm -rf /workspace/nvflare

# Install the controller package
COPY ./controller /workspace/controller
RUN python3 -m pip install /workspace/controller
RUN rm -rf /workspace/controller

# Copy source code to image
RUN apt update && apt install -y git
COPY . /MediSwarm
RUN cd /MediSwarm && git clean -f .
RUN apt remove -y git && apt autoremove -y

# Set the Docker image name
LABEL name="nvflare-pt-dev:3dcnn"