#!/usr/bin/env bash

REMOTE_HOST="172.24.4.65"
REMOTE_USER="mediswarm-upload"
REMOTE_BASE="/srv/mediswarm/live"

LOG_SYNC_INTERVAL=30
CKPT_SYNC_INTERVAL=180

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"