name = "challenge_1DivideAndConquer"
resource_spec {}
deploy_map {
  app = [
    "@ALL"
  ]
}
min_clients = 8
mandatory_clients = [
  "CAM_1",
  "VHIO_1",
  "USZ_1",
  "RUMC_1",
  "MHA_1",
  "RSH_1",
  "UMCU_1",
  "UKA_1"
]
